USE sakila;

#1 List the number of films per category.

SELECT c.name AS category, COUNT(f.film_id) AS film_count
FROM category c
JOIN film_category fc USING(category_id)
JOIN film f USING (film_id)
GROUP BY c.name
ORDER BY film_count DESC;

#2 Retrieve the store ID, city, and country for each store.
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM store s
JOIN address a USING (address_id)
JOIN city ci USING(city_id)
JOIN country co USING (country_id);


#3 Calculate the total revenue generated by each store in dollars.
 
SELECT s.store_id, SUM(p.amount) AS total_amount
FROM payment p
JOIN staff s USING (staff_id)
GROUP BY s.store_id;


#4 Determine the average running time of films for each category.
SELECT c.name AS category, AVG(f.length) AS average_running_time
FROM category c
JOIN film_category fc USING(category_id)
JOIN film f USING(film_id)
GROUP BY c.name
ORDER BY average_running_time DESC;

